//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xBiddingMaintenance_1
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class bid
    {
        public int BidId { get; set; }
        public Nullable<int> MethodRef { get; set; }
        public string BidName { get; set; }
        public string Description { get; set; }
        public Nullable<int> SuitRef { get; set; }
        public Nullable<int> StageRef { get; set; }
        public Nullable<int> ShapeRef { get; set; }
        public Nullable<int> PointRangeRef { get; set; }
        public Nullable<int> ltcRef { get; set; }
        public Nullable<int> BidBoxRef { get; set; }
        public Nullable<int> ConventionRef { get; set; }
        public Nullable<int> Protective { get; set; }
        public int OpponentBidRef { get; set; }
        public int PartnerBidRef { get; set; }
        public Nullable<int> SuitQualityRef { get; set; }
        public Nullable<int> FourCardMajorRef { get; set; }
        public Nullable<int> Balanced { get; set; }
    
        public virtual balancedaction balancedaction { get; set; }
        public virtual bidbox bidbox { get; set; }
        public virtual convention convention { get; set; }
        public virtual fourcardmajoraction fourcardmajoraction { get; set; }
        public virtual losingtrickcountrange losingtrickcountrange { get; set; }
        public virtual pointrange pointrange { get; set; }
        public virtual protectiveaction protectiveaction { get; set; }
        public virtual shape shape { get; set; }
        public virtual stage stage { get; set; }
        public virtual suitquality suitquality { get; set; }
        public virtual suitname suitname { get; set; }
        public virtual method method { get; set; }
    }
}
