//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xBiddingMaintenance_1
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class losingtrickcountrange
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public losingtrickcountrange()
        {
            this.bids = new ObservableCollection<bid>();
        }
    
        public int ltcId { get; set; }
        public string ltcDescription { get; set; }
        public byte Min { get; set; }
        public byte Max { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<bid> bids { get; set; }
    }
}
