//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xBiddingMaintenance_1
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class referencedsuit
    {
        public int ReferencedSuitId { get; set; }
        public string Description { get; set; }
    }
}
