//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xBiddingMaintenance_1
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class setting
    {
        public int SettingsId { get; set; }
        public int UserRef { get; set; }
        public string SettingName { get; set; }
        public string SettingDescription { get; set; }
        public int SettingValue { get; set; }
    }
}
